### ISSUE TITLE
Two different http clients are used; there should only be one

### ISSUE THREAD

**Issue by AubreyHewes** [kingsquare/communibase-connector-php#12]
Both `curl` and `file_get_contents` are used.
 * Requires separate configuration; enhancing complexity.
 * * _Possible_ configuration is not used for `file_get_contents`
* Possible overrides will not work on both

**Comment by AubreyHewes** [comment]
Connector should use one ring; possibly guzzle. Else the `getBinary` method should also use curl.

**Comment by fruitl00p** [comment]
This has been fixed in the 2.0.0 release by moving to GuzzleHttp
