### ISSUE TITLE
Need to be able to override basic curl options

### ISSUE THREAD

**Issue by AubreyHewes** [kingsquare/communibase-connector-php#8]
Should be able to override curl options (possible protected getCurlOptions method?)

Example:
Service is not available.. current timeout is the curl default (minute?)

Usage requirement:
Timeout should be configurable (in some way). Timeout can then be set to 10s (for example). This helps alleviate the pain of a broken api..

**Comment by fruitl00p** [comment]
This too has been fixed with the release of 2.0.0 and the GuzzleHttp integration.

**Comment by AubreyHewes** [comment]
subclassing and overloading the `getClient` method now makes this possible.. though there is still no way to `setClientOptions` without subclassing..

**Comment by fruitl00p** [comment]
But subclassing would be the safer way to go anyway ;)
